#############################################################################
# Makefile for building: libset_list_tracker_arm64-v8a.so
# Generated by qmake (3.1) (Qt 6.1.2)
# Project:  set_list_tracker.pro
# Template: app
# Command: C:\Qt\6.1.2\mingw81_64\bin\qmake.exe -o Makefile set_list_tracker.pro -qtconf C:/Qt/6.1.2/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = C:\Users\tomiw\AppData\Local\Android\Sdk\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang
CXX           = C:\Users\tomiw\AppData\Local\Android\Sdk\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -target aarch64-linux-android23 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -target aarch64-linux-android23 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -g -std=gnu++1z -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IC:\Qt\6.1.2\android_arm64_v8a\include -IC:\Qt\6.1.2\android_arm64_v8a\include\QtQuick -IC:\Qt\6.1.2\android_arm64_v8a\include\QtOpenGL -IC:\Qt\6.1.2\android_arm64_v8a\include\QtGui -IC:\Qt\6.1.2\android_arm64_v8a\include\QtQmlModels -IC:\Qt\6.1.2\android_arm64_v8a\include\QtQml -IC:\Qt\6.1.2\android_arm64_v8a\include\QtNetwork -IC:\Qt\6.1.2\android_arm64_v8a\include\QtCore -I. -IC:\Qt\6.1.2\android_arm64_v8a\mkspecs\android-clang
QMAKE         = C:\Qt\6.1.2\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\6.1.2\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\6.1.2\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = cmd /c move
TAR           = 
COMPRESS      = 
DISTNAME      = libset_list_tracker_arm64-v8a.so1.0.0
DISTDIR = C:\Users\tomiw\Documents\Qt_projects\set_list_tracker\.tmp\libset_list_tracker_arm64-v8a.so1.0.0
LINK          = C:\Users\tomiw\AppData\Local\Android\Sdk\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -target aarch64-linux-android23 -fno-limit-debug-info
LFLAGS        = -Wl,-soname,libset_list_tracker_arm64-v8a.so -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) C:/Qt/6.1.2/android_arm64_v8a/lib/libQt6Quick_arm64-v8a.so C:/Qt/6.1.2/android_arm64_v8a/lib/libQt6OpenGL_arm64-v8a.so C:/Qt/6.1.2/android_arm64_v8a/lib/libQt6Gui_arm64-v8a.so C:/Qt/6.1.2/android_arm64_v8a/lib/libQt6QmlModels_arm64-v8a.so C:/Qt/6.1.2/android_arm64_v8a/lib/libQt6Qml_arm64-v8a.so C:/Qt/6.1.2/android_arm64_v8a/lib/libQt6Network_arm64-v8a.so C:/Qt/6.1.2/android_arm64_v8a/lib/libQt6Core_arm64-v8a.so -lGLESv2   -llog -lz -lm -ldl -lc
AR            = C:\Users\tomiw\AppData\Local\Android\Sdk\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar cqs
RANLIB        = C:\Users\tomiw\AppData\Local\Android\Sdk\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.obj \
		qrc_qml.obj
DIST          =   main.cpp
QMAKE_TARGET  = libset_list_tracker_arm64-v8a.so
DESTDIR       = 
TARGET        = libset_list_tracker_arm64-v8a.so


first: all
####### Build rules

libset_list_tracker_arm64-v8a.so:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: set_list_tracker.pro C:\Qt\6.1.2\android_arm64_v8a\mkspecs\android-clang\qmake.conf C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\spec_pre.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\unix.conf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\linux.conf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\sanitize.conf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\gcc-base.conf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\gcc-base-unix.conf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\clang.conf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\qdevice.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\device_config.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\qconfig.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_ext_freetype.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_ext_libpng.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_bodymovin_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_input_support_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_linguist.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_linguist_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmldom_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_tools_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qt_functions.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qt_config.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\android-clang\qmake.conf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\spec_post.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\spec_post.prf \
		.qmake.stash \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\exclusive_builds.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\toolchain.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\default_pre.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\default_pre.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\resolve_config.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\resolve_config.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\default_post.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qml_debug.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\android.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\resources_functions.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\android_deployment_settings.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\warn_on.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qt.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\resources.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\moc.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\unix\opengl.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\unix\thread.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qmake_use.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\file_copies.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\testcase_targets.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\exceptions.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\yacc.prf \
		C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\lex.prf \
		set_list_tracker.pro \
		qml.qrc
	$(QMAKE) -o Makefile set_list_tracker.pro -qtconf C:/Qt/6.1.2/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\spec_pre.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\unix.conf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\linux.conf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\sanitize.conf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\gcc-base.conf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\gcc-base-unix.conf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\common\clang.conf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\qdevice.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\device_config.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\qconfig.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_ext_freetype.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_ext_libpng.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_bodymovin_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core5compat_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_help.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_input_support_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsanimation_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssettings_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labssharedimage_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_linguist.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_linguist_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_network.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_openglwidgets_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmldom_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlmodels_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3d_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick3dutils_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicklayouts_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_scxmlqml_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_shadertools_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachine_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_statemachineqml_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_svgwidgets_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_tools_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qt_functions.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qt_config.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\android-clang\qmake.conf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\spec_post.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\spec_post.prf:
.qmake.stash:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\exclusive_builds.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\toolchain.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\default_pre.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\default_pre.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\resolve_config.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\resolve_config.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\default_post.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qml_debug.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\android.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\resources_functions.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\android\android_deployment_settings.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\warn_on.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qt.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\resources.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\moc.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\unix\opengl.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\unix\thread.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\qmake_use.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\file_copies.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\testcase_targets.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\exceptions.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\yacc.prf:
C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\lex.prf:
set_list_tracker.pro:
qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile set_list_tracker.pro -qtconf C:/Qt/6.1.2/android_arm64_v8a/bin/target_qt.conf -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE


all: Makefile libset_list_tracker_arm64-v8a.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)\
	$(COPY_FILE) --parents C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents main.cpp $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

aab: apk_install_target
	C:\Qt\6.1.2\mingw81_64\bin\androiddeployqt.exe --input C:/Users/tomiw/Documents/Qt_projects/set_list_tracker/android-set_list_tracker-deployment-settings.json --output C:/Users/tomiw/Documents/Qt_projects/set_list_tracker/android-build --aab --apk C:\Users\tomiw\Documents\Qt_projects\set_list_tracker\android-build\set_list_tracker.apk

apk: apk_install_target
	C:\Qt\6.1.2\mingw81_64\bin\androiddeployqt.exe --input C:/Users/tomiw/Documents/Qt_projects/set_list_tracker/android-set_list_tracker-deployment-settings.json --output C:/Users/tomiw/Documents/Qt_projects/set_list_tracker/android-build --apk C:\Users\tomiw\Documents\Qt_projects\set_list_tracker\android-build\set_list_tracker.apk

apk_install_target: first
	$(MAKE) -f $(MAKEFILE) INSTALL_ROOT=C:\Users\tomiw\Documents\Qt_projects\set_list_tracker\android-build install

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		C:\Qt\6.1.2\mingw81_64\bin\rcc.exe \
		Main_Page.qml \
		Load_page.qml \
		Set_List_Drawer.qml \
		Setlist_Popup_Menu.qml \
		AddSong_Drawer.qml \
		main.qml \
		Menu_Icon.qml \
		javascript.js \
		MyListModel.qml \
		assets\feo_logo2.png
	C:\Qt\6.1.2\mingw81_64\bin\rcc.exe -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\data\dummy.cpp
	C:\Users\tomiw\AppData\Local\Android\Sdk\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -target aarch64-linux-android23 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -g -std=gnu++1z -Wall -W -dM -E -o moc_predefs.h C:\Qt\6.1.2\android_arm64_v8a\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.obj: main.cpp C:\Qt\6.1.2\android_arm64_v8a\include\QtGui\QGuiApplication \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtGui\qguiapplication.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtGui\qtguiglobal.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qglobal.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qconfig.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qtcore-config.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qsystemdetection.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qprocessordetection.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcompilerdetection.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qtypeinfo.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcontainerfwd.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qsysinfo.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qlogging.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qflags.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qatomic.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qbasicatomic.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qgenericatomic.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qatomic_cxx11.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qglobalstatic.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qmutex.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qnumeric.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qversiontagging.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtGui\qtgui-config.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcoreapplication.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstring.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qchar.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringview.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qbytearray.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qrefcount.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qnamespace.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qtmetamacros.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qarraydata.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qpair.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qarraydatapointer.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qarraydataops.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcontainertools_impl.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qbytearrayalgorithms.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qbytearrayview.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringliteral.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringalgorithms.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qanystringview.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qutf8stringview.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringtokenizer.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringbuilder.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qobject.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qobjectdefs.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qlist.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qhashfunctions.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qiterator.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qbytearraylist.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringlist.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qalgorithms.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringmatcher.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcoreevent.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qscopedpointer.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qmetatype.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcompare.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qvarlengtharray.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qdatastream.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qiodevicebase.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qiterable.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qmetacontainer.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcontainerinfo.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qtaggedpointer.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qmath.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qobject_impl.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qproperty.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qshareddata.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qpropertyprivate.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qeventloop.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qdebug.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qhash.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qmap.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qshareddata_impl.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qtextstream.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qstringconverter.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qset.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qcontiguouscache.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qsharedpointer.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtGui\qwindowdefs.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtGui\qwindowdefs_win.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtGui\qinputmethod.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qlocale.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qvariant.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qpoint.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qsize.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qmargins.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\QQmlApplicationEngine \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmlapplicationengine.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmlengine.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qurl.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qjsengine.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qjsvalue.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qtqmlglobal.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qtqml-config.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtNetwork\qtnetworkglobal.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtNetwork\qtnetwork-config.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qjsmanagedvalue.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qjsprimitivevalue.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qjsnumbercoercion.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmldebug.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqml.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmlprivate.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmlparserstatus.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmllist.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\QMetaType \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmlpropertyvaluesource.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qpointer.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qversionnumber.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtCore\qmetaobject.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmlerror.h \
		C:\Qt\6.1.2\android_arm64_v8a\include\QtQml\qqmlabstracturlinterceptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qrc_qml.obj: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.obj qrc_qml.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\arm64-v8a mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\arm64-v8a & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\arm64-v8a exit 1
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\arm64-v8a\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\arm64-v8a\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\arm64-v8a 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

